load("@prelude//toolchains:rust.bzl", "system_rust_toolchain")
load("@prelude//toolchains:python.bzl", "system_python_bootstrap_toolchain")
load("@prelude//toolchains:cxx.bzl", "system_cxx_toolchain")
load("@prelude//tests:test_toolchain.bzl", "noop_test_toolchain")
load(":remote_test_execution.bzl", "noop_remote_test_execution_toolchain")

system_rust_toolchain(
    name = "rust",
    visibility = ["PUBLIC"],
)

system_python_bootstrap_toolchain(
    name = "python_bootstrap",
    visibility = ["PUBLIC"],
)

system_cxx_toolchain(
    name = "cxx",
    visibility = ["PUBLIC"],
)

noop_test_toolchain(
    name = "test",
    visibility = ["PUBLIC"],
)

noop_remote_test_execution_toolchain(
    name = "remote_test_execution",
    visibility = ["PUBLIC"],
)