load("@prelude//rust:cargo_package.bzl", "cargo")

cargo.rust_binary(
    name = "rue",
    srcs = glob(["src/**/*.rs"]),
    crate_root = "src/main.rs",
    edition = "2024",
    deps = [
        "//crates/rue-compiler:rue-compiler",
        "//crates/rue-codegen:rue-codegen",
    ],
    visibility = ["PUBLIC"],
)