load("@prelude//rust:cargo_package.bzl", "cargo")

cargo.rust_library(
    name = "rue-compiler",
    srcs = glob(["src/**/*.rs"]),
    crate_root = "src/lib.rs",
    edition = "2024",
    deps = [
        "//crates/rue-ast:rue-ast",
        "//crates/rue-lexer:rue-lexer",
        "//crates/rue-parser:rue-parser",
        "//:salsa",
    ],
    visibility = ["PUBLIC"],
)