name: Buck2 Extended

on:
  push:
    branches: [ trunk ]
  pull_request:
    branches: [ trunk ]
  # Also run weekly to catch Buck2 updates
  schedule:
    - cron: '0 0 * * 0'

jobs:
  buck2-extended:
    name: Buck2 Extended Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust stable
      uses: dtolnay/rust-toolchain@stable
    
    - name: Install Buck2
      uses: dtolnay/install-buck2@latest
    
    - name: Install Reindeer
      run: |
        cargo install --git https://github.com/facebookincubator/reindeer reindeer
    
    - name: Verify Buck2 configuration
      run: |
        buck2 audit cell prelude
        buck2 targets toolchains//:
        buck2 audit providers toolchains//:rust --target-platforms=prelude//platforms:default
        buck2 audit providers toolchains//:python_bootstrap --target-platforms=prelude//platforms:default
        buck2 audit providers toolchains//:cxx --target-platforms=prelude//platforms:default
    
    - name: Build all crates individually
      run: |
        buck2 build //crates/rue-ast:rue-ast
        buck2 build //crates/rue-lexer:rue-lexer
        buck2 build //crates/rue-parser:rue-parser
        buck2 build //crates/rue-compiler:rue-compiler
        buck2 build //crates/rue-codegen:rue-codegen
        buck2 build //crates/rue:rue
    
    - name: Test reindeer buckify
      run: |
        # Backup current state
        cp BUCK BUCK.backup
        # Run reindeer to regenerate
        reindeer buckify
        # Check that the build still works
        buck2 build //crates/rue:rue
        # Restore backup
        mv BUCK.backup BUCK
    
    - name: Buck2 query tests
      run: |
        buck2 uquery "deps(//crates/rue:rue)"
        buck2 cquery "deps(//crates/rue:rue)" --target-platforms=prelude//platforms:default
    
    - name: Check for unused dependencies
      run: |
        # This will help us keep dependencies clean
        buck2 uquery "kind(rust_library, deps(//crates/rue:rue))"