name: Documentation

on:
  push:
    branches: [ trunk ]
  pull_request:
    branches: [ trunk ]

jobs:
  docs:
    name: Check Documentation
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust stable
      uses: dtolnay/rust-toolchain@stable
    
    - name: Check Rust documentation
      run: cargo doc --all --no-deps
    
    - name: Check for broken internal links in docs
      run: cargo doc --all --no-deps 2>&1 | grep -i "warning.*intra.*doc" && exit 1 || true
    
    - name: Validate CLAUDE.md and spec.md exist
      run: |
        test -f CLAUDE.md
        test -f docs/spec.md
        echo "✓ Core documentation files present"
    
    - name: Check for TODO markers in code
      run: |
        echo "Checking for TODO/FIXME markers..."
        if grep -r "TODO\|FIXME" crates/ --include="*.rs"; then
          echo "Found TODO/FIXME markers - this is fine for development"
        else
          echo "No TODO/FIXME markers found"
        fi
    
    - name: Validate Cargo.toml files
      run: |
        for toml in $(find . -name "Cargo.toml"); do
          echo "Checking $toml"
          cargo metadata --manifest-path "$toml" --format-version 1 > /dev/null
        done